#include <iostream>

#include "HEAR_ROS_BRIDGE/ROSUnit.hpp"
#include "HEAR_ROS_BRIDGE/ROSUnit_BroadcastData.hpp"
#include "HEAR_ROS_BRIDGE/ROSUnit_ControlOutputSubscriber.hpp"
#include "HEAR_ROS_BRIDGE/ROSUnit_EmptyClnt.hpp"
#include "HEAR_ROS_BRIDGE/ROSUnit_EmptySrv.hpp"
#include "HEAR_ROS_BRIDGE/ROSUnit_Factory.hpp"
#include "HEAR_ROS_BRIDGE/ROSUnit_FloatPub.hpp"
#include "HEAR_ROS_BRIDGE/ROSUnit_FloatSub.hpp"
#include "HEAR_ROS_BRIDGE/ROSUnit_InfoSubscriber.hpp"
#include "HEAR_ROS_BRIDGE/ROSUnit_Optitrack.hpp"
#include "HEAR_ROS_BRIDGE/ROSUnit_Point2DPub.hpp"
#include "HEAR_ROS_BRIDGE/ROSUnit_Point2DSub.hpp"
#include "HEAR_ROS_BRIDGE/ROSUnit_PointPub.hpp"
#include "HEAR_ROS_BRIDGE/ROSUnit_PointSub.hpp"
#include "HEAR_ROS_BRIDGE/ROSUnit_RestNormSettings.hpp"
#include "HEAR_ROS_BRIDGE/ROSUnit_RestNormSettingsClnt.hpp"
#include "HEAR_ROS_BRIDGE/ROSUnit_RTK.hpp"
#include "HEAR_ROS_BRIDGE/ROSUnit_SetFloatClnt.hpp"
#include "HEAR_ROS_BRIDGE/ROSUnit_SetFloatSrv.hpp"
#include "HEAR_ROS_BRIDGE/ROSUnit_SetIntClnt.hpp"
#include "HEAR_ROS_BRIDGE/ROSUnit_SetIntSrv.hpp"
#include "HEAR_ROS_BRIDGE/ROSUnit_SetPointClnt.hpp"
#include "HEAR_ROS_BRIDGE/ROSUnit_SetPointsClnt.hpp"
#include "HEAR_ROS_BRIDGE/ROSUnit_SetPointSrv.hpp"
#include "HEAR_ROS_BRIDGE/ROSUnit_SetPointsSrv.hpp"
#include "HEAR_ROS_BRIDGE/ROSUnit_SetPoseClnt.hpp"
#include "HEAR_ROS_BRIDGE/ROSUnit_SetPosesClnt.hpp"
#include "HEAR_ROS_BRIDGE/ROSUnit_SetPoseSrv.hpp"
#include "HEAR_ROS_BRIDGE/ROSUnit_SetPosesSrv.hpp"
#include "HEAR_ROS_BRIDGE/ROSUnit_SetVectorClnt.hpp"
#include "HEAR_ROS_BRIDGE/ROSUnit_SetVectorSrv.hpp"
#include "HEAR_ROS_BRIDGE/ROSUnit_UpdateControllerSrv.hpp"
#include "HEAR_ROS_BRIDGE/ROSUnit_UpdateControllerClnt.hpp"
#include "HEAR_ROS_BRIDGE/ROSUnit_IMU.hpp"

int main(int argc, char **argv)
{
	std::cout << "HI (:" << std::endl;
}